#!/bin/sh
# burnerpad installer — demoted, checksum-pinned, no-sudo (ARCHITECTURE.md §24).
#
# The documented way to use this script is: DOWNLOAD IT, READ IT, THEN RUN IT.
# Its trust root is the text you are reading, not the CDN it fetches from:
# the release repository, version, and per-target SHA256s below are embedded at
# release time, so a swapped artifact fails the hash check.
#
#   sh install.sh              install to ~/.local/bin (or $BURNERPAD_INSTALL_DIR)
#   sh install.sh --verify-only  download + verify, install nothing
#
# No sudo, no eval, fails closed on unknown arguments, OS, or architecture.
set -euf

# ── release pins — REGENERATED BY THE RELEASE WORKFLOW; do not edit by hand ──
REPO="burnerpad/burnerpad-cli"
VERSION="0.0.0-dev"
SHA256_linux_amd64="0000000000000000000000000000000000000000000000000000000000000000"
SHA256_linux_arm64="0000000000000000000000000000000000000000000000000000000000000000"
SHA256_darwin_amd64="0000000000000000000000000000000000000000000000000000000000000000"
SHA256_darwin_arm64="0000000000000000000000000000000000000000000000000000000000000000"
# ─────────────────────────────────────────────────────────────────────────────

VERIFY_ONLY=0
usage() {
    echo "usage: sh install.sh [--verify-only]" >&2
    exit 2
}
case "$#" in
    0) ;;
    1)
        [ "$1" = "--verify-only" ] || usage
        VERIFY_ONLY=1
        ;;
    *) usage ;;
esac

DIR="${BURNERPAD_INSTALL_DIR:-$HOME/.local/bin}"

if [ "$VERSION" = "0.0.0-dev" ]; then
    echo "this is the unreleased template installer; use a release copy from" >&2
    echo "https://github.com/$REPO/releases" >&2
    exit 1
fi

os=$(uname -s)
arch=$(uname -m)
case "$os" in
    Linux) os=linux ;;
    Darwin) os=darwin ;;
    *) echo "unsupported OS: $os (Windows: use the release zip)" >&2; exit 1 ;;
esac
case "$arch" in
    x86_64 | amd64) arch=amd64 ;;
    aarch64 | arm64) arch=arm64 ;;
    *) echo "unsupported architecture: $arch" >&2; exit 1 ;;
esac

case "${os}_${arch}" in
    linux_amd64) want=$SHA256_linux_amd64 ;;
    linux_arm64) want=$SHA256_linux_arm64 ;;
    darwin_amd64) want=$SHA256_darwin_amd64 ;;
    darwin_arm64) want=$SHA256_darwin_arm64 ;;
    *) echo "no pinned hash for ${os}/${arch}" >&2; exit 1 ;;
esac
[ -n "$want" ] || { echo "no pinned hash for ${os}/${arch}" >&2; exit 1; }

archive="burnerpad_${VERSION}_${os}_${arch}.tar.gz"
url="https://github.com/$REPO/releases/download/v${VERSION}/${archive}"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

echo "fetching $url"
curl -fsSL -o "$tmp/$archive" "$url"

got=$( (sha256sum "$tmp/$archive" 2>/dev/null || shasum -a 256 "$tmp/$archive") | cut -d' ' -f1)
if [ "$got" != "$want" ]; then
    echo "CHECKSUM MISMATCH for $archive" >&2
    echo "  expected: $want" >&2
    echo "  got:      $got" >&2
    echo "refusing to install." >&2
    exit 1
fi
echo "checksum verified: $got"

if [ "$VERIFY_ONLY" = 1 ]; then
    echo "--verify-only: nothing installed."
    exit 0
fi

tar -xzf "$tmp/$archive" -C "$tmp" burnerpad
mkdir -p "$DIR"
install -m 0755 "$tmp/burnerpad" "$DIR/burnerpad"
echo "installed $DIR/burnerpad ($VERSION)"
case ":$PATH:" in
    *":$DIR:"*) ;;
    *) echo "note: $DIR is not on your PATH" ;;
esac
